
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  postgres-explorer:
    image: postgres-explorer:dev
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - postgres


volumes:
  postgres_data:
