[project]
name = "postgres-explorer"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.4",
    "psycopg[binary]>=3.2.9",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-django>=4.11.1",
]
